package com.example.opsmonitor.domain.model.enums;

public enum AuditAction {
  SERVICE_CREATED,
  HEALTH_SNAPSHOT_RECORDED,
  SERVICE_STATUS_CHANGED,
  FAILED_JOB_RETRY_REQUESTED,
  INCIDENT_NOTE_CREATED,
  INCIDENT_ACKNOWLEDGED,
  INCIDENT_RESOLVED
}
